name: openai_agent_demo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  shadcn_ui: ^0.16.3
  path: ^1.9.0
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  objectbox: ^4.0.3
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - .env
