name: openai_agent_demo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  shadcn_ui: ^0.16.3
  path: ^1.9.0
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.2
  openai_realtime_dart: ^0.0.3+1
  record: ^5.2.0
  permission_handler: ^11.3.0
  flutter_sound: ^9.17.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  objectbox_generator: any
  riverpod_generator: ^2.6.3

dependency_overrides:
  openai_realtime_dart:
    path: pkg/langchain_dart/packages/openai_realtime_dart

flutter:
  uses-material-design: true
  assets:
    - .env
